# (from: https://github.com/codecov/example-node/blob/master/.travis.yml)
language: node_js
sudo: false
node_js:
  - "9"
  - "8"
  - "7"
install:
  - npm install
script:
  # NOTE: Just build for test
  - npm run build
